examples: Fix linker error in examplestest by adding shared.cc dependency
Fix undefined reference errors when building examplestest target

The examplestest target was failing to link due to missing Address class
method implementations (size() and as_sockaddr()) that are called from
util.cc. These methods are implemented in shared.cc but were not included
in the examplestest_SOURCES.

Changes:
- Add shared.cc and shared.h to examplestest_SOURCES 
- Remove duplicate shared.cc/shared.h from ENABLE_EXAMPLE_WOLFSSL section
  to avoid build conflicts

This aligns examplestest with other targets (qtlsclient, qtlsserver, etc.)
that already include shared.cc through SERVER_SRCS or CLIENT_SRCS.

Fixes linker errors:
  undefined reference to `ngtcp2::Address::size() const'
  undefined reference to `ngtcp2::Address::as_sockaddr() const'