Add note about need libev for build examples
(May be also add check if libev is available because the build fail :
In file included from client.cc:38:0:
client.h:38:16: fatal error: ev.h: No such file or directory